always set the verifier

diff --git a/templates/review_skip_list.sh.j2 b/templates/review_skip_list.sh.j2
--- a/templates/review_skip_list.sh.j2
+++ b/templates/review_skip_list.sh.j2
@@ -2,13 +2,6 @@
 while read -r skip_list
 do
     environment=$(echo "${skip_list}" | sed 's_/home/rally/deployments/__' | sed 's/-skip-list.yml//')
-    {{ rally_cmd }} deployment use "${environment}"
-    verifier_id=$({{ rally_cmd }} verify list-verifiers | grep "${environment}" | awk '{print($2)}')
-    if [ -z "${verifier_id}" ]; then
-        echo "Verifier ID not found for '${environment}'"
-        exit 1
-    fi
-    {{ rally_cmd }} verify use-verifier --id "${verifier_id}"
     if [ -e "/home/rally/deployments/.${environment}_ok_tests" ]; then
         rm "/home/rally/deployments/.${environment}_ok_tests"
     fi
@@ -16,6 +9,13 @@ do
     while read -r test
     do
         if [ -n "${test}" ] && [ "${test}" != "---" ] && [ "${test}" != "..." ]; then
+            {{ rally_cmd }} deployment use "${environment}"
+            verifier_id=$({{ rally_cmd }} verify list-verifiers | grep "${environment}" | awk '{print($2)}')
+            if [ -z "${verifier_id}" ]; then
+                echo "Verifier ID not found for '${environment}'"
+                exit 1
+            fi
+            {{ rally_cmd }} verify use-verifier --id "${verifier_id}"
             echo "Testing '${test}'..."
             {{ rally_cmd }} verify start --detailed --pattern "${test}" > "/home/rally/deployments/.${environment}_tests_results/${test}_result"
             grep 'Success: 0' "/home/rally/deployments/.${environment}_tests_results/${test}_result"
