select verifier before clean up

diff --git a/templates/tempest_run.sh.j2 b/templates/tempest_run.sh.j2
--- a/templates/tempest_run.sh.j2
+++ b/templates/tempest_run.sh.j2
@@ -11,6 +11,14 @@ if [[ "$TERM" =~ "screen" ]]; then
 source /home/rally/rally/bin/activate
 {%- endif -%}
 
+{{ rally_cmd }} deployment use {{ item.key }}
+verifier_id=$({{ rally_cmd }} verify list-verifiers | grep {{ item.key }} | awk '{print($2)}')
+if [ -z "${verifier_id}" ]; then
+  echo 'Verifier ID not found for {{ item.key }}'
+  exit 1
+fi
+{{ rally_cmd }} verify use-verifier --id "${verifier_id}"
+
 {%- if item.value.tempest_manual_forloop_cleanup %}
 # Remove any resources with tempest in their names. Perhaps acceptable in a devel/test environment.
 source /home/rally/.rally/openrc
@@ -22,14 +30,8 @@ for project in $({{ openstack_cmd }}openstack project list -f csv -c ID -c Name 
 for domain in $({{ openstack_cmd }}openstack domain list -f csv -c ID -c Name|tr -d '"'|grep tempest-test_domain|cut -d "," -f1); do echo \#Disabling and deleting Tempest domain $domain; {{ openstack_cmd }}openstack domain set --disable $domain; openstack domain delete $domain; done
 {%- endif %}
 
-{{ rally_cmd }} deployment use {{ item.key }}
-verifier_id=$({{ rally_cmd }} verify list-verifiers | grep {{ item.key }} | awk '{print($2)}')
-if [ -z "${verifier_id}" ]; then
-  echo 'Verifier ID not found for {{ item.key }}'
-  exit 1
-fi
-{{ rally_cmd }} verify use-verifier --id "${verifier_id}"
 {{ rally_cmd }} verify start --skip-list {{ deployments_folder }}/{{ item.key }}-skip-list.yml --concurrency {{ concurrency }} --detailed "${@}"
+
 {%- if item.value.tempest_manual_forloop_cleanup %}
 # Remove any resources with tempest in their names. Perhaps acceptable in a devel/test environment.
 source /home/rally/.rally/openrc
